### ISSUE TITLE
Timeseries execution fails

### ISSUE THREAD

**Issue by larjohn** [openbudgets/DAM#6]
02:51:27 default: okfgr_dm.okfgr_server.dm_okfgr('/ocpu/library/OBeU/R/ts.obeu', prediction_steps='-1', tsdata='not given') (7c21a8be-d3e9-4f3f-a22c-d925b955d99d)
['curl', '-d', 'tsdata=not given', '-d', 'prediction_steps=-1', 'http://okfnrg.math.auth.gr/ocpu/library/OBeU/R/ts.obeu']
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    67    0    31  100    36      7      8  0:00:04  0:00:04 --:--:--     8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0curl: (6) Could not resolve host: okfnrg.math.auth.grUnparsable argument

02:51:38 subprocess.CalledProcessError: Command '['curl', 'http://okfnrg.math.auth.grUnparsable argument: not given/print']' returned non-zero exit status 6
Traceback (most recent call last):
  File "/opt/DAM/env/lib/python3.5/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/opt/DAM/env/lib/python3.5/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/DAM/env/lib/python3.5/site-packages/okfgr_dm/okfgr_server.py", line 17, in dm_okfgr
    result = subprocess.check_output(['curl', OK_GREECE_ROOT+result_endpoint+'/print']).decode("utf-8")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['curl', 'http://okfnrg.math.auth.grUnparsable argument: not given/print']' returned non-zero exit status 6
Traceback (most recent call last):
  File "/opt/DAM/env/lib/python3.5/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/opt/DAM/env/lib/python3.5/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/DAM/env/lib/python3.5/site-packages/okfgr_dm/okfgr_server.py", line 17, in dm_okfgr
    result = subprocess.check_output(['curl', OK_GREECE_ROOT+result_endpoint+'/print']).decode("utf-8")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['curl', 'http://okfnrg.math.auth.grUnparsable argument: not given/print']' returned non-zero exit status 6
02:51:38 Moving job to 'failed' queue

What is this unparseable argument all about?

**Comment by HimmelStein** [comment]
['curl', '-d', 'tsdata=not given', '-d', 'prediction_steps=-1', 'http://okfnrg.math.auth.gr/ocpu/library/OBeU/R/ts.obeu']
this means that you have not give value to the 'tsdata' parameter, which should be the dataset.
